apiVersion: v1
kind: Service
metadata:
  name: nacritan-backend-api
  labels:
    tier: nacritan-backend
spec:
  selector:
    app: api
    tier: nacritan-backend
  ports:
  - protocol: TCP
    port: 5000
