apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacritan-backend-code-api
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
