apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nacritan
  name: nacritan-sqlite-db
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
