apiVersion: v1
kind: Service
metadata:
  name: nacritan-lb
  labels:
    tier: nacritan-backend
spec:
  type: LoadBalancer
  selector:
    app: python
    tier: nacritan-backend
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 5001
    protocol: TCP
    name: sqlite-web
