apiVersion: v1
kind: Service
metadata:
  namespace: nacritan
  name: nacritan-lb
  labels:
    tier: nacritan-backend
spec:
  type: LoadBalancer
  selector:
    app: nginx
    tier: nacritan-backend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
