apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacridian-backend-code-php
spec:
  storageClassName: cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
