apiVersion: v1
kind: Service
metadata:
  name: nacritan-backend-sqlite-web
  labels:
    tier: nacritan-backend
spec:
  selector:
    app: sqlite-web
    tier: nacritan-backend
  ports:
  - protocol: TCP
    port: 5001
