apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nacritan
  name: nacritan-backend-backup
  labels:
    tier: nacritan-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup
      tier: nacritan-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backup
        tier: nacritan-backend
    spec:
      restartPolicy: Always

      containers:
      - name: nacritan-backend-backup
        image: lordslair/easydbbackup:1.1.0
        imagePullPolicy: Always
        env:
        - name: SQLITE
          value: '<SQLITE>' # Boolean (True|False)
        - name: SQLITE_FILE
          value: '<SQLITE_FILE>'
        - name: SQLITE_PATH
          value: '<SQLITE_PATH>'
        - name: PCA_USER
          value: 'pca'
        - name: PCA_HOST
          value: '<PCA_HOST>'
        - name: PCA_DIR
          value: '<PCA_DIR>'
        - name: PCA_PASS
          value: '<PCA_PASS>'
        volumeMounts:
        - mountPath: /db
          name: db

      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: nacritan-backend-sqlite-db
